name: Eavesdropper
version: '${project.version}'
main: com.simondmc.eavesdropper.Eavesdropper
api-version: '1.21'
authors: [SimonDMC]
description: Adds spyware to Minecraft
website: simondmc.com

commands:
  eavesdrop:
  msg: